### ISSUE TITLE
Problem with PHP 7.1 at first session initialization and save

### ISSUE THREAD

**Issue by COil** [M6Web/RedisBundle#42]
Symfony raises an error 500:

> An exception has been thrown during the rendering of a template ("Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions)").

When reloading the page it will work. It's just at the 1st session init.

The load session mustn't return null but an empty string.

https://stackoverflow.com/questions/48245296/php-custom-session-handler-problems-php-7-1?rq=1

**Comment by COil** [comment]
Seems the bundle version we use is outdated. I'll check with new version.

**Comment by Oliboy50** [comment]
it seems that you're right
=>  http://php.net/manual/en/function.session-start.php#120589

even our current bundle version returns null
=> https://github.com/M6Web/RedisBundle/blob/master/src/Redis/RedisSessionHandler.php#L59

so I'd be ok to approve [your PR](https://github.com/COil/RedisBundle/commit/d11aab4a3342e87c602c6cbc56b0a6a2dc954da5) when you open it

**Comment by COil** [comment]
Done.

**Comment by COil** [comment]
Closing this, it is outdated.
